### ISSUE TITLE
Onderzoek mogelijke systemen (Randy)

### ISSUE THREAD

**Issue by osmanseker** [Mikail3/VideoWall#5]

**Comment by Villadelfia** [comment]
1 master raspberry pi. Hierop staat een automount script. Als je een usb stick insteekt dan mount hij die en begint hij te broadcasten op het lokale network via UDP multicast. Een packet bevat een frame en de id van de master.

Een raspberry pi per scherm, daarop draait simpele client software: Hij luistert voor broadcast UDP packets van de master met de ID waarvoor hij geconfigureerd is. Als hij zo een packet ontvangt toont hij dan daar de "viewport" van zoals geconfigureerd.

In short: 
master moet gewoon de ID  en wifi configureren.
client moet de master ID en wifi configureren, en ook een viewport.

Dit kan allemaal op de boot partitie die je via windows kan editen.
